### ISSUE TITLE
[epic] Refactoring & Make Code Climate happy

### ISSUE THREAD

**Issue by zhuyifei1999** [Toollabs/video2commons#22]
[![Code Climate](https://codeclimate.com/github/Toollabs/video2commons/badges/gpa.svg)](https://codeclimate.com/github/Toollabs/video2commons)

- [ ] Simplify duplicated code
- [ ] Simplify call parameters
- [ ] Make parts `packages`
- [ ] Unit testing
